---
title: "week 10"
author: "Chong Zhang"
date: "March 20, 2018"
output: html_document
---

#14.1
##14.1.1 Use the mean/mode imputation method to impute values for the missing data.
```{r cache=TRUE}
library(dplyr)
# load the data set, change "?" to NA
breast_cancer = read.csv('breast-cancer-wisconsin.data.txt', sep = ',', header = F, na.strings = '?')%>%tbl_df()

# change the attributes name accordingly
attribute_name = c('Sample_code_number', 'Clump_Thickness', 'Uniformity_of_Cell_Size', 'Uniformity_of_Cell_Shape', 'Marginal_Adhesion', 'Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin', 'Normal_Nucleoli', 'Mitoses', 'Class')
colnames(breast_cancer) = attribute_name

# using dplyr's mutate_all funcion to replace the missing data with the column mean. However since the number of nuclei can not be a number with fraction. So I will round it up.
imputed = mutate_all(breast_cancer, funs(ifelse(is.na(.), round(mean(., na.rm = T)), .)))


```

## 14.1.2 Use regression to impute values for the missing data.
```{r cache=TRUE}
# load the caret package
library(caret)

set.seed(666)
# set the train_control parameter. Cros validation with 5 folds
tc =  trainControl(method = 'cv', number = 5)

# train the Generalized Linear Model with Stepwise Feature Selection. Sample code number is not included.
lr = train(Bare_Nuclei~., breast_cancer[,-1], method = 'glmStepAIC', trControl = tc, na.action = na.omit)

# The R-squared is:
print(lr$results[3])

#get the index of all NA in te Bare_Nuclei column
index = which(is.na(unlist(breast_cancer$Bare_Nuclei)))

# creat a copy of the breast_cancer data
imputed = breast_cancer

#apply the linear regression model to predict the bear nuclei number
for (i in index){
  # predict the bear nuclei number
  bear_nuclei = predict(lr, breast_cancer[i, -c(1,7)])
  print(bear_nuclei)
  # update the bear nuclei number 
  imputed[i,7] = round(bear_nuclei)
}

```


## 14.1.3 Use regression to impute values for the missing data.
```{r cache=TRUE}
#since only Bare Nuclei column has missing data, we can build the linear regression model for it
lr = lm(Bare_Nuclei~., breast_cancer[,-1], na.action=na.omit)

#get the index of all NA in te Bare_Nuclei column
index = which(is.na(unlist(breast_cancer$Bare_Nuclei)))

imputed = breast_cancer


```